name: Bug Report
description: Create a bug report
type: bug

title: "[Bug]: "
labels: ["bug"]
projects: []

assignees:
  - Tandashi

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  - type: dropdown
    id: project
    attributes:
      label: Project
      description: What project is this bug related to?
      options:
        - 'Pirate Radio: Labs'
        - 'Pirate Radio: Client'
        - 'Pirate Radio: Mod Listing'
        - 'KnockoutCity SDK (TypeScript)'
    validations:
      required: true
  
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
 
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Linux
        - MacOS
        - Other
    validations:
      required: true
